name: Build & Push to GHCR

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up QEMU (for multi-arch builds, optional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: shamim-codemoly
          password: ${{ secrets.GHCR_TOKEN }}

      # Build & Push image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/shamim-codemoly/dokploy_test:latest
            ghcr.io/shamim-codemoly/dokploy_test:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/shamim-codemoly/dokploy_test:cache
          cache-to: type=registry,ref=ghcr.io/shamim-codemoly/dokploy_test:cache,mode=max
